<a id="inicio"></a>
<br><br><br>
<div align="left">
<h1><font size=6>Pandas</font></h1>
    <h2><font color="#5E5E5E" size=5>9. Acceso condicional a datos</font>  </h2>
<br><br><br><br>
</div>


<div align="right">
<font color="#B51700" size=4><b>Análisis y visualización de datos</b></font><br><br>
<font  size=3>Máster Universitario en Ingeniería Informática</font><br>
<font  size=3>Máster Universitario en Big Data y Computación en la Nube</font><br>
<font size=3>Máster Universitario en Inteligencia Artificial</font><br><br>
<font color="#5E5E5E" size=3><b>Luis de la Ossa  &nbsp;&nbsp;</b></font><span style="background-color:#B51700; color:white; padding:2px 6px; font-family:Arial, sans-serif;font-weight:bold;font-size:18px;">UCLM</span>
</div>

---


A menudo, las tareas de análisis de datos y visualización conllevan la selección o eliminación de un subconjunto de los datos en base a algún criterio. Esto se denomina ***selección condicional o filtrado***.

<div class="alert alert-block alert-info">

<i class="fa fa-info-circle" aria-hidden="true"></i>
Por adecuar los términos al nombre de los métodos de *pandas*, vamos a referirnos a selección condicional cuando se haga en base a los valores de los datos, y filtrado cuando lo hagamos según el valor del índice y las columnas.
</div>

---

En esta libreta se trabajará con una versión del `DataFrame` de prueba `df_productos`, utilizado en libretas anteriores, a la que se añadieron algunas columnas.

In [1]:
import pandas as pd

df_productos = pd.read_csv('data/productos_prep.csv', index_col=0, dtype={'C.P':str})
df_productos

,Nombre,Producto,Apellido,Compra,Venta,C.P,Entregado,Localidad
Tienda 1,Álvaro,Queso manchego,Álvarez,10.0,22.0,02001,True,Albacete
Tienda 2,Benito,Vino manchego,Benitez,10.0,14.5,02001,True,Albacete
Tienda 3,Fernando,Jamón extremeño,Fernández,35.0,50.0,02003,NaN,Albacete
Tienda 4,Martín,Aceite andaluz,Martínez,12.0,20.0,02004,NaN,Albacete
Tienda 2,Hernán,Azafrán manchego,Hernández,10.0,0.0,02004,True,Albacete

---

## <font color="#5E5E5E">1. Selección condicional</font>
### <font color="#5E5E5E">  Indexación mediante valores booleanos </font>

#### <font color="#5E5E5E">  El método `.loc[ ]` </font>

Para ilustrar la selección condicional se recurrirá a la columna `df_productos['Producto']` del `DataFrame` `df_productos`.

In [2]:
s_productos = df_productos['Producto']
s_productos

Tienda 1      Queso manchego
Tienda 2       Vino manchego
Tienda 3     Jamón extremeño
Tienda 4      Aceite andaluz
Tienda 2    Azafrán manchego
Name: Producto, dtype: str

`Series.loc[]` / `DataFrame.loc[]` acepta **también** como argumento una secuencia de valores de tipo *booleano*, del mismo tamaño que la `Series` o el `DataFrame` (número de filas), y en el que cada valor de la colección determina si el elemento o fila en esa posición se accede o no.

In [3]:
s_productos.loc[[False, True, True, True, False]] # Accede a todos los elementos menos el primero y el último

Tienda 2      Vino manchego
Tienda 3    Jamón extremeño
Tienda 4     Aceite andaluz
Name: Producto, dtype: str

In [4]:
df_productos.loc[[False, True, True, True, False]]  # Accede a todas los filas menos la primera y la última

,Nombre,Producto,Apellido,Compra,Venta,C.P,Entregado,Localidad
Tienda 2,Benito,Vino manchego,Benitez,10.0,14.5,02001,True,Albacete
Tienda 3,Fernando,Jamón extremeño,Fernández,35.0,50.0,02003,NaN,Albacete
Tienda 4,Martín,Aceite andaluz,Martínez,12.0,20.0,02004,NaN,Albacete

El método `DataFrame.loc[sel, col]` permite acceder a datos concretos. Admite que una de los ejes se indexe con una colección de booleanos, y el otro con una colección de etiquetas.

In [5]:
df_productos.loc[[False, True, True, True, False], ['Producto', 'Venta']]
#df_productos.loc[[False, True, True, True, False], :]
#df_productos.loc[[False, True, True, True, False],[True, True, True, False, False, False, False, False, False]]
#df_productos.loc[['Tienda 1', 'Tienda 2'],[True, True, True, False, False, False, False, False, False]]
#df_productos.loc[:,[True, True, True, False, False, False, False, False, False]]

                 Producto  Venta
Tienda 2    Vino manchego   14.5
Tienda 3  Jamón extremeño   50.0
Tienda 4   Aceite andaluz   20.0

#### <font color="#5E5E5E">  Uso del operador `[ ]` </font>

Hasta ahora, el operador `[ ]` se ha utilizado *exclusivamente* para acceder a *columnas* mediante su posición o etiqueta del índice. 

El acceso **a elementos/filas** mediante una **colección de valores de tipo *booleano*** se puede hacer también a través del operador `[ ]`.

In [6]:
#s_productos[[False, True, True, True, False]]  # Elementos de la serie
df_productos[[False, True, True, True, False]]  # Filas del DataFrame

,Nombre,Producto,Apellido,Compra,Venta,C.P,Entregado,Localidad
Tienda 2,Benito,Vino manchego,Benitez,10.0,14.5,02001,True,Albacete
Tienda 3,Fernando,Jamón extremeño,Fernández,35.0,50.0,02003,NaN,Albacete
Tienda 4,Martín,Aceite andaluz,Martínez,12.0,20.0,02004,NaN,Albacete

Sin embargo, el acceso mediante `DataFrame[sel]`, cuando `sel` es una colección de valores *booleanos*, se hace **solamente** a nivel de filas. No permite acceder a columnas, ni a filas/columnas.

In [ ]:
#df_productos[[True, True, True, False, False, False, False, False, False]]   # Columnas: no funciona
#df_productos[[False, True, True, True, False], ['Producto', 'Venta']]        # Filas/Columnas: no funciona
#df_productos[[False, True, True, True, False], [True, True, True, False, False, False, False, False, False]] # Filas/Columnas: no funciona

<div class="alert alert-block alert-danger">

<i class="fa fa-exclamation-triangle" aria-hidden="true"></i> Cabe recordar que, hasta el momento, la operación `DataFrame[sel]` se utilizaba **solamente** para acceder a **columnas**, y aceptaba **un** argumento, que podía ser el nombre de una columna, o una colección de nombres de columnas. En el caso de que el argumento sea una colección de valores *booleanos*, `DataFrame[sel]` accede **solamente a filas**.
    
 Por tanto, en el caso de los *DataFrame*, hay **dos usos posibles** de `DataFrame[sel]` que dependen del valor que toma `sel`: 
  
* cuando es un ***string*** o una colección de ***strings***, se utiliza para acceder a **columnas**; 
* cuando es un una colección de  valores ***booleanos***, se utiliza para acceder a **filas**.     

Aunque estas convenciones puedan inducir cierta confusión, ***tienen una razón de ser*** : la mayoría de los accesos a columnas se hacen mediante su nombre o nombres; y la mayoría de los accesos a filas se hacen mediante selección condicional. En ambos casos se utiliza `DataFrame[sel]` por ser la notación más cómoda.
</div>

Es relativamente común, sin embargo ver ejemplos en los que se utiliza `DataFrame[sel][col]`. En este caso, el resultado es el esperado, pero es necesario conocer más en profundidad su comportamiento para evitar efectos no deseados en el caso de *escrituras*, ya que en realidad **se accede solamente a filas**, y posteriormente a las columnas del `DataFrame` resultante, que está sujeto a  *copy-on-write*.

In [ ]:
df_productos[[False, True, True, True, False]][['Producto', 'Venta']]

### <font color="#5E5E5E">  Selección condicional </font>

La colección de valores de tipo *booleano* utilizada para seleccionar filas puede ser también una `Series`. En el siguiente ejemplo, se utiliza una operación vectorizada `>` para hacer una comparación entre los valores de la columna `df_productos['Venta']` y un escalar. El resultado es una `Series` cuyo índice es el mismo que el del `DataFrame`, y sus valores son los resultados de la comparación.

In [ ]:
df_productos

In [ ]:
s_values = df_productos['Venta']>15
s_values

Los valores de la `Series` resultante, una *colección de valores booleanos*,  pueden utilizarse para acceder al propio `DataFrame` (se alinéan los índices).

In [ ]:
df_productos[df_productos['Venta']>15] # Productos con valor de venta mayor que 15

<div class="alert alert-block alert-info">

<i class="fa fa-info-circle" aria-hidden="true"></i>
Esta operación, en la que se han seleccionado unas filas en función al valor de una (en este caso) de sus columnas se denomina **selección condicional**, y es muy común en el trabajo con datos. 
</div>



Es posible construir expresiones condicionales más complejas mediante el uso de los operadores `&` (*and*), `|` (*or*), y `~` (*not*), que operan sobre las máscaras elemento a elemento.

In [ ]:
df_productos[(df_productos['Venta']>15) & (df_productos['Compra']>10)]
#df_productos[(df_productos['Venta']>20) | ((df_productos['Compra']>10) & (df_productos['Compra']<30))]

<div class="alert alert-block alert-danger">

<i class="fa fa-exclamation-triangle" aria-hidden="true"></i>
Debido a que los operadores binarios tienen precedencia sobre las comparaciones, es *muy importante* utilizar paréntesis. 
</div>

In [ ]:
#df_productos[df_productos['Venta']>15 & df_productos['Compra']>10] # Error

<div class="alert alert-block alert-info">

<i class="fa fa-info-circle" aria-hidden="true"></i>
`DataFrame.loc[]` puede recibir también una función que actúe sobre el propio `DataFrame`. Esto permite incorporar selección condicional al *method chaining* donde la selección puede hacerse a partir de un `DataFrame` intermedio.
</div>

In [ ]:
df_productos.loc[lambda df: df['Venta']>10]

#### <font color="#5E5E5E"> `DataFrame.query()`</font>

`DataFrame.query()` selecciona filas mediante una expresión escrita como cadena de texto. Podemos referirnos directamente a las columnas por su nombre y combinar condiciones con `and`, `or` y `not`. La sintaxis se basa en Python, pero el analizador predeterminado de pandas incorpora reglas propias.

In [ ]:
df_productos.query("Venta > 15 and Localidad=='Albacete'")

<div class="alert alert-block alert-info">

<i class="fa fa-info-circle" aria-hidden="true"></i>
`index` permite referirse al índice dentro del `string` con la consulta. También es posible referirse a variables en el entorno anteponiéndoles el caracter `@`.
</div>

In [ ]:
tienda = "Tienda 2"

df_productos.query("index == @tienda")
#df_productos.query("index == @tienda and Venta > 10")

### <font color="#5E5E5E">  Algunos métodos de utilidad para la construcción de expresiones condicionales</font>

#### <font color="#5E5E5E"> `Series.isin()` / `DataFrame.isin()`</font>

El método `Series.isin(col)` acepta como argumento una colección de valores, `col`, y devuelve `True` o `False` para cada elemento de la `Series` dependiendo de si éste se encuentra o no en `col`. Es un método de __suma utilidad__ ya que permite seleccionar filas en función de si el valor de una columna está o no dentro de un conjunto.

In [ ]:
df_productos['C.P'].isin(['02001','02004'])

In [ ]:
df_productos[df_productos['C.P'].isin(['02001','02004'])]

El método `DataFrame.isin(col)` acepta como argumento un diccionario en el que las claves corresponden a columnas, y los valores a la colección utilizada para hacer la selección de cada columna. El resultado del método es un *DataFrame* con el resultado de la operación condicional, que es necesario procesar convenientemente.

In [ ]:
cond = {'Compra':[10, 12], 'C.P':['02001','02004']} 
df_productos[df_productos.isin(cond)[['Compra','C.P']].all(axis=1)]

#### <font color="#5E5E5E"> `Series.between()` </font>

El método `Series.between(left, right)` se utiliza para operar sobre series numéricas. Para cada elemento, devuelve `True` si está en el intervalo `[left, right]`, y `False` en caso contrario. Equivale a `(serie >= left) & (serie <= right)`.

In [ ]:
df_productos

In [ ]:
df_productos[df_productos['Venta'].between(10,22)]

#### <font color="#5E5E5E"> Manejo de valores perdidos: `Series.isna()`/`Series.isnull()` y `Series.notna()`/`Series.notnull()` </font>

También existen las funciones `Series.isna()/Series.isnull()` y `Series.notna()/Series.notnull()`, que permiten determinar qué elementos de la serie son `NaN` (o `None`, `pd.NA`, `NaT`, dependiendo del tipo de datos) o no lo son, y pueden ser utilizados en la selección condicional.

In [ ]:
df_productos['Entregado'].isna()
#df_productos[df_productos['Entregado'].notna()] #Accede a las filas en las que se conoce el valor de Entregado

La clase `DataFrame` también implementa estos métodos

In [ ]:
df_productos.isna().sum(axis=0)   # Calcula el número de valores perdidos en cada columna

#### <font color="#5E5E5E"> Condiciones sobre *strings*: `Series.str` </font>

Algunos métodos que operan sobre `Series` de `strings` devuelven *Series* de valores *booleanos*, y pueden ser utilizados en la construcción de valores condicionales [**( + inf )**](https://pandas.pydata.org/docs/user_guide/text.html#method-summary)`

<div class="alert alert-block alert-info">
    
<i class="fa fa-info-circle" aria-hidden="true"></i>

Los métodos de texto que devuelven condiciones permiten seleccionar filas. El tratamiento de los ausentes depende del dtype de la serie. Para indicar explícitamente que un producto desconocido no cumple la condición, podemos utilizar `na=False` (aunque es el valor del parámetro por defecto).


</div>

In [ ]:
df_productos.loc['Tienda 3', 'Producto'] = pd.NA
df_productos

In [ ]:
df_productos[df_productos['Producto'].str.startswith('A', na=False)] # Problema con los NA
#df_productos [df_productos['Producto'].notna() & df_productos['Producto'].str.startswith('A')]

#### <font color="#5E5E5E"> Uso de funciones más complejas </font>

También es posible utilizar expresiones más complejas, siempre y cuando devuelvan una `Series` de valores *booleanos* con el mismo índice del `DataFrame`.

In [ ]:
(df_productos['Venta']-df_productos['Compra'])>10
df_productos[(df_productos['Venta']-df_productos['Compra'])>10]

Estas operaciones también se pueden hacer mediante `DataFrame.query()`.

In [ ]:
df_productos.query("Venta - Compra > 10")

Estas funciones pueden ser el resultado de aplicar una función a cada fila del `DataFrame`.

In [ ]:
def pct_benefit(row):
    return (100 * (row['Venta']-row['Compra']) / row['Compra']) > 50

df_productos[df_productos.apply(pct_benefit, axis=1)]

En realidad, para esa función en concreto, como el criterio puede expresarse mediante operaciones sobre columnas completas, no necesitamos llamar a una función Python para cada fila. La siguiente expresión construye la misma máscara de forma vectorizada.

In [ ]:
df_productos[(100 * (df_productos['Venta']-df_productos['Compra']) / df_productos['Compra']) > 50]

---

## <font color="#5E5E5E">2. Filtrado (selección por valor de los índices) </font>

El método `Series.filter()`/`DataFrame.filter()` permite seleccionar filas o columnas en función de las etiquetas del índice correspondiente. Se utiliza principalmente con índices de tipo `string`, y admite un parámetro, `axis`, que determina el índice utilizado. Además, acepta otros argumentos/parámetros principales:

* `like`, para indicar que las etiquetas seleccionadas *deben contener* una cadena; 
* `regex`, que indica que las etiquetas seleccionados deben emparejar con una expresión regular;
* `items`, que determina el conjunto de etiquetas que han de ser seleccionada. Admite etiquetas numéricas.

In [ ]:
# Prepara una version del DataFrame para las pruebas

df_productos.loc['Tienda 3', 'Producto'] = 'Jamón'
df_productos_p = df_productos.reset_index(names='Tienda').set_index('Producto')
df_productos_p

In [ ]:
#df_productos_p.filter(like='manchego', axis=0).head()   # Filas cuyo índice contiene 'manchego'
df_productos_p.filter(regex=r'\w+ \w+', axis=0).head()   # Filas que contienen la expresión regular (al menos dos palabras)

<div class="alert alert-block alert-danger">

<i class="fa fa-exclamation-triangle" aria-hidden="true"></i> En el caso de filtrado por filas el método, junto con el argumento `items`, solamente funciona cuando el índice es único. En ese caso, es equivalente a `DataFrame.loc[]`. En el caso de las columnas es equivalente a la selección mediante `[ ]`.  `DataFrame.filter()` omite las etiqueas que no existen.
</div>

In [ ]:
df_productos.filter(items=['Venta', 'No existe'])
# df_productos.filter(items=['Venta', 'No existe'], axis=1) # Equivalente

#### <font color="#5E5E5E"> Filtrado mediante operaciones sobre el índice </font>

Es posible acceder al índice de una `Series` o  `DataFrame` a través del atributo `Series.index` / `DataFrame.index`. Aunque el índice es una estructura de datos *especial*, en el sentido de que gestiona el acceso eficiente a los datos, admite algunas operaciones del mismo modo que los *arrays NumPy* o las `Series`.

In [ ]:
df_productos_p.index.str.contains("manchego")
#df_productos_p[df_productos_p.index.str.contains("manchego")]

A través de la selección condicional, se pueden eliminar valores duplicados del índice. El método `Index.duplicated()` devuelve una colección de valores de tipo *booleano* que reflejan si un valor está duplicado o no. El parámetro `keep` determina si se mantiene alguno de los valores. Esta serie se puede utilizar para hacer selección condicional.

In [ ]:
#df_productos.index.duplicated(keep='first')
df_productos[~df_productos.index.duplicated(keep='first')]

`Index.drop_duplicates()` devuelve un índice, por lo que no se puede utiliza para esto




---


## <font color="#5E5E5E">3. Reemplazo condicional de valores</font>

Existen también métodos que acceden a los datos a través de expresiones condicionales, pero con el objetivo de alterar los valores.

### <font color="#5E5E5E">  `Series.where()` / `DataFrame.where()`</font>

El método `Series.where()` / `DataFrame.where()` selecciona los valores/filas que cumplen una condición, y al resto les asigna un valor que, por defecto es `NaN`, pero puede ser pasado como parámetro.

In [ ]:
#df_productos[df_productos['Venta'] > 20]
df_productos.where(df_productos['Venta']>20)   
#df_productos.where(df_productos['Venta']>20, '-----')   # Ojo! Convierte todas las columnas a `object`

Del mismo modo que la indexación condicional, `Series.where()` / `DataFrame.where()` acepta expresiones condicionales más complejas.

In [ ]:
df_productos.where((df_productos['Compra']>20) &  (df_productos['Venta']>20), '----')

`Series.where()` / `DataFrame.where()` también acepta una función que actúe sobre filas y devuelva un booleano como condición.

In [ ]:
df_productos.where(pct_benefit, '---', axis=0)

### <font color="#00586D">  `Series.mask()` / `DataFrame.mask()`</font>

El método `Series.mask()` / `DataFrame.mask()` hace la función opuesta al anterior. Es decir, sustituye el valor en las filas que cumplen la condición.

In [ ]:
df_productos.mask(df_productos['Venta']>20)   
#df_productos.mask(df_productos['Venta']>20, '-----')

<div class="alert alert-block alert-info">
    
<i class="fa fa-info-circle" aria-hidden="true"></i>
Existe un uso más avanzado de estas funciones, en las que los valores seleccionados/descartados pueden sustituirse con información de otra `Series` o `Dataframe` [**(+ inf)**](https://pandas.pydata.org/docs/user_guide/indexing.html#the-where-method-and-masking).

</div>

<br>
<div align="right">
<a href="#inicio"><font size=5 color="#B51700"><i class="fa fa-arrow-circle-up" aria-hidden="true"></i></font></a>
</div>

---

<div align="right">
<font size=5 color="#B51700"><i class="fa fa-coffee" aria-hidden="true"></i></font>
</div>