<a id="inicio"></a>
<br><br><br>
<div align="left">
<h1><font size=6>Pandas</font></h1>
    <h2><font color="#5E5E5E" size=5>15. Índices de varios niveles </font> </h2>
<br><br><br><br>
</div>


<div align="right">
<font color="#B51700" size=4><b>Análisis y visualización de datos</b></font><br><br>
<font  size=3>Máster Universitario en Ingeniería Informática</font><br>
<font  size=3>Máster Universitario en Big Data y Computación en la Nube</font><br>
<font size=3>Máster Universitario en Inteligencia Artificial</font><br><br>
<font color="#5E5E5E" size=3><b>Luis de la Ossa  &nbsp;&nbsp;</b></font><span style="background-color:#B51700; color:white; padding:2px 6px; font-family:Arial, sans-serif;font-weight:bold;font-size:18px;">UCLM</span>
</div>

---

In [1]:
import pandas as pd
pd.__version__

'3.0.6'

En esta libreta se utilizará el archivo `county.txt`, con datos sobre el censo de Estados Unidos.

In [2]:
df_county = pd.read_csv('data/county.txt', sep='\t')
df_county.head()

,name,state,pop2000,pop2010,fed_spend,poverty,homeownership,multiunit,income,med_income
0,Autauga County,Alabama,43671.0,54571,6.068095,10.6,77.5,7.2,24568,53255
1,Baldwin County,Alabama,140415.0,182265,6.139862,12.2,76.7,22.6,26469,50147
2,Barbour County,Alabama,29038.0,27457,8.752158,25.0,68.0,11.1,15875,33219
3,Bibb County,Alabama,20826.0,22915,7.122016,12.6,82.9,6.6,19918,41770
4,Blount County,Alabama,51024.0,57322,5.130910,13.4,82.0,3.7,21070,45549

---

*pandas* permite utilizar varios niveles de indexación, tanto para filas como para columnas. En este tutorial se describen los conceptos necesarios para el uso más común de estas estructuras. Se puede encontrar más información al respecto en la documentación [**( + inf )**](https://pandas.pydata.org/pandas-docs/stable/user_guide/advanced.html). 


Cuando se utilizan *varias columnas* (generalmente dos) como índice del `DataFrame`, se crea un índice de varios niveles que se organizan de **forma jerárquica**. Este tipo de índice se denomina también multiíndice.

In [3]:
df_county.set_index(['state','name'], inplace=True)
df_county.head(10)

                          pop2000  pop2010  fed_spend  poverty  homeownership  \
state   name
Alabama Autauga County    43671.0    54571   6.068095     10.6           77.5
        Baldwin County   140415.0   182265   6.139862     12.2           76.7
        Barbour County    29038.0    27457   8.752158     25.0           68.0
        Bibb County       20826.0    22915   7.122016     12.6           82.9
        Blount County     51024.0    57322   5.130910     13.4           82.0
        Bullock County    11714.0    10914   9.973062     25.3           76.9
        Butler County     21399.0    20947   9.311835     25.0           69.0
        Calhoun County   112249.0   118572  15.439218     19.5           70.7
        Chambers County   36583.0    34215   8.613707     20.3           71.4
        Cherokee County   23988.0    25989   7.104621     17.6           77.5

                         multiunit  income  med_income
state   name
Alabama Autauga County         7.2   24568       53255
        Baldwin County        22.6   26469       50147
        Barbour County        11.1   15875       33219
        Bibb County            6.6   19918       41770
        Blount County          3.7   21070       45549
        Bullock County         9.9   20289       31602
        Butler County         13.7   16916       30659
        Calhoun County        14.3   20574       38407
        Chambers County        8.7   16626       31467
        Cherokee County        4.3   21322       40690

<div class="alert alert-block alert-info">

<i class="fa fa-info-circle" aria-hidden="true"></i> Si se pasa una lista de columnas a `index_col` al leer un `DataFrame` con `pd.read_csv()`, también crea un índice de varios niveles.
</div>

Cuando se utiliza un índice a varios niveles, el acceso natural a filas se hace mediante **tuplas** cuyo tamaño corresponde al número de índices, y con los valores del índice en cada nivel.

In [7]:
df_county.loc[('Alabama','Bibb County')]          # Accede a una fila. Es recomendable utilizar una tupla.
#df_county.loc['Alabama','Bibb County']           # Se permite esta notación, pero puede inducir errores.

pop2000          20826.000000
pop2010          22915.000000
fed_spend            7.122016
poverty             12.600000
homeownership       82.900000
multiunit            6.600000
income           19918.000000
med_income       41770.000000
Name: (Alabama, Bibb County), dtype: float64

In [8]:
#df_county.loc[['Alabama','Bibb County'], ['pop2000', 'pop2010']] # No funciona, porque utiliza una lista en lugar de una tupla.
df_county.loc[('Alabama','Bibb County'), ('pop2000', 'pop2010')]

pop2000    20826.0
pop2010    22915.0
Name: (Alabama, Bibb County), dtype: float64

<div class="alert alert-block alert-warning">

<i class="fa fa-exclamation-circle" aria-hidden="true"></i>
__Importante__: Hablamos de varios niveles porque pueden ser más de dos (aunque rara vez se da esta circunstancia). 
</div>

No es necesario especificar valores en todos los niveles para localizar elementos. Es posible omitir los valores ___a partir de___ un nivel.

In [9]:
df_county.loc['Alabama']
#df_county.loc['Alabama', ['pop2000', 'pop2010']]

,pop2000,pop2010,fed_spend,poverty,homeownership,multiunit,income,med_income
name,,,,,,,,
Autauga County,43671.0,54571,6.068095,10.6,77.5,7.2,24568,53255
Baldwin County,140415.0,182265,6.139862,12.2,76.7,22.6,26469,50147
Barbour County,29038.0,27457,8.752158,25.0,68.0,11.1,15875,33219
Bibb County,20826.0,22915,7.122016,12.6,82.9,6.6,19918,41770
Blount County,51024.0,57322,5.130910,13.4,82.0,3.7,21070,45549
...,...,...,...,...,...,...,...,...
Tuscaloosa County,164875.0,194656,7.777685,19.7,63.3,25.4,22546,42311
Walker County,70713.0,67023,10.173716,18.6,77.7,6.6,20516,37191
Washington County,18097.0,17581,7.829987,19.7,83.0,2.6,18824,36431
Wilcox County,13183.0,11670,13.639417,38.5,76.8,6.0,12573,23491
Winston County,24843.0,24484,8.743874,20.6,73.8,6.1,18055,33685

Los índices de varios niveles permiten _slicing_ sobre el nivel principal.

In [10]:
df_county.loc['Alabama':'California'].tail()

                             pop2000  pop2010  fed_spend  poverty  \
state      name
California Tulare County    368021.0   442179   5.419988     22.9
           Tuolumne County   54501.0    55365   8.138264     11.7
           Ventura County   753197.0   823318   7.379247      9.2
           Yolo County      168660.0   200849  11.132796     17.1
           Yuba County       60219.0    72155  12.109237     20.0

                            homeownership  multiunit  income  med_income
state      name
California Tulare County             59.3       14.4   17966       43851
           Tuolumne County           70.2        8.6   25483       47462
           Ventura County            66.4       20.2   32348       75348
           Yolo County               54.1       30.6   27420       57077
           Yuba County               59.8       17.8   19937       46807

Es posible ordenar el `DataFrame` en función del índice jerárquico. En ese caso, la jerarquía se utiliza también en la ordenación.

In [11]:
df_county.sort_index(inplace=False)

                            pop2000  pop2010  fed_spend  poverty  \
state   name
Alabama Autauga County      43671.0    54571   6.068095     10.6
        Baldwin County     140415.0   182265   6.139862     12.2
        Barbour County      29038.0    27457   8.752158     25.0
        Bibb County         20826.0    22915   7.122016     12.6
        Blount County       51024.0    57322   5.130910     13.4
...                             ...      ...        ...      ...
Wyoming Sweetwater County   37613.0    43806   5.062138      8.2
        Teton County        18251.0    21294   6.236968      8.2
        Uinta County        19742.0    21118   4.549105     12.1
        Washakie County      8289.0     8533   8.713817      5.6
        Weston County        6644.0     7208   6.694784      7.9

                           homeownership  multiunit  income  med_income
state   name
Alabama Autauga County              77.5        7.2   24568       53255
        Baldwin County              76.7       22.6   26469       50147
        Barbour County              68.0       11.1   15875       33219
        Bibb County                 82.9        6.6   19918       41770
        Blount County               82.0        3.7   21070       45549
...                                  ...        ...     ...         ...
Wyoming Sweetwater County           73.7       14.6   30961       69828
        Teton County                60.8       31.9   42224       70271
        Uinta County                73.7       17.0   24460       58346
        Washakie County             70.9       10.0   28557       48379
        Weston County               77.9        6.5   28463       53853

[3143 rows x 8 columns]

Cuando el `DataFrame` **está ordenado**, es posible hacer slicing con tuplas.

In [12]:
#df_county.loc[('Alabama','Coosa County'):('Wyoming','Carbon County')] # No está ordenado y devuelve error
df_county.sort_index().loc[('Alabama','Coosa County'):('Wyoming','Carbon County')].head()

                          pop2000  pop2010  fed_spend  poverty  homeownership  \
state   name
Alabama Coosa County      12202.0    11539   7.839761     16.0           83.7
        Covington County  37631.0    37765   9.461856     19.0           74.0
        Crenshaw County   13665.0    13906   9.650295     17.7           67.8
        Cullman County    77483.0    80406   7.760627     16.7           74.7
        Dale County       49129.0    50251  25.774791     14.8           61.2

                          multiunit  income  med_income
state   name
Alabama Coosa County            1.9   19209       35560
        Covington County        6.1   19822       33852
        Crenshaw County         9.2   19793       35140
        Cullman County          8.5   20284       38567
        Dale County            13.2   21722       43353

También se puede ordenar el `DataFrame` según un nivel determinado  del índice.

In [13]:
df_county.sort_index(level=1, inplace=True)
df_county.head()

,,pop2000,pop2010,fed_spend,poverty,homeownership,multiunit,income,med_income
state,name,,,,,,,,
South Carolina,Abbeville County,26167.0,25417,6.687335,20.7,77.4,7.7,16653,33143
Louisiana,Acadia Parish,58861.0,61773,7.444660,20.1,69.8,7.1,18116,37261
Virginia,Accomack County,38305.0,33164,13.547069,15.6,74.1,5.6,22766,41372
Idaho,Ada County,300904.0,392365,7.957794,10.2,69.6,18.0,27915,55835
Iowa,Adair County,8243.0,7682,10.259177,10.6,75.8,9.6,23497,45202

In [14]:
df_county.sort_index(inplace=True) # Restaura el orden

Mediante la función `DataFrame.xs()` se puede acceder a los datos especificando el nivel del índice. Esto permite la indexación simple con índices en cualquier nivel.

In [16]:
df_county.xs('Park County', level=1) # Existen tres condados con el mismo nombre, en diferentes estados.
#df_county.xs('Park County', level=1, drop_level=False) # Preserva el nivel
#df_county.xs('Park County', level="name") # Equivalente

,pop2000,pop2010,fed_spend,poverty,homeownership,multiunit,income,med_income
state,,,,,,,,
Colorado,14523.0,16206,3.801802,6.2,87.9,1.3,31663,64098
Montana,15694.0,15636,6.880852,13.6,70.4,11.1,24717,38830
Wyoming,25786.0,28205,10.813260,9.0,68.7,10.5,26203,46637

Existen varios métodos que permiten crear un índice de varios niveles [**( + inf )**](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.MultiIndex.html).  Por ejemplo, el índice de varios niveles puede crearse a través de una lista de tuplas. En este ejemplo, se crea para un índice de dos niveles para las columnas.

In [17]:
# Crea la lista de tuplas
level1 = ['population', 'population', 'money', 'money', 'money','money','money','money']
level2 = df_county.columns
tuples = list(zip(level1,level2))
#tuples

# Crea el índice de dos niveles
mi_columns = pd.MultiIndex.from_tuples(tuples, names=['ámbito', 'indicador'])
#mi_columns

# Establece un índice de dos niveles en las columnas.
df_county.columns = mi_columns
df_county.head()

ámbito                 population             money                        \
indicador                 pop2000 pop2010 fed_spend poverty homeownership
state   name
Alabama Autauga County    43671.0   54571  6.068095    10.6          77.5
        Baldwin County   140415.0  182265  6.139862    12.2          76.7
        Barbour County    29038.0   27457  8.752158    25.0          68.0
        Bibb County       20826.0   22915  7.122016    12.6          82.9
        Blount County     51024.0   57322  5.130910    13.4          82.0

ámbito
indicador              multiunit income med_income
state   name
Alabama Autauga County       7.2  24568      53255
        Baldwin County      22.6  26469      50147
        Barbour County      11.1  15875      33219
        Bibb County          6.6  19918      41770
        Blount County        3.7  21070      45549

<div class="alert alert-block alert-info">

<i class="fa fa-exclamation-circle" aria-hidden="true"></i>
Existen otros métodos como `from_arrays()`, `from_product()` o `from_frame()`.
</div>

El método `DataFrame.swaplevel()` permite intercambiar dos niveles en la jerarquía de índices. Utiliza el parámetro `axis` para determinar sobre qué índice actúa. No acepta el parámetro `inplace`, pero **devuelve una copia** del `DataFrame`.

In [18]:
df_county.swaplevel(i=1,j=0, axis=1).head() # Cambia el índice de columnas

indicador                 pop2000    pop2010 fed_spend poverty homeownership  \
ámbito                 population population     money   money         money
state   name
Alabama Autauga County    43671.0      54571  6.068095    10.6          77.5
        Baldwin County   140415.0     182265  6.139862    12.2          76.7
        Barbour County    29038.0      27457  8.752158    25.0          68.0
        Bibb County       20826.0      22915  7.122016    12.6          82.9
        Blount County     51024.0      57322  5.130910    13.4          82.0

indicador              multiunit income med_income
ámbito                     money  money      money
state   name
Alabama Autauga County       7.2  24568      53255
        Baldwin County      22.6  26469      50147
        Barbour County      11.1  15875      33219
        Bibb County          6.6  19918      41770
        Blount County        3.7  21070      45549

In [19]:
# df_county.head() # No altera el DataFrame original

Otra posibilidad es reordenarlos con `DataFrame.reorder_levels()`. Las filas mantienen su posición.

In [20]:
df_county.reorder_levels(['name','state']).head()

ámbito                 population             money                        \
indicador                 pop2000 pop2010 fed_spend poverty homeownership
name           state
Autauga County Alabama    43671.0   54571  6.068095    10.6          77.5
Baldwin County Alabama   140415.0  182265  6.139862    12.2          76.7
Barbour County Alabama    29038.0   27457  8.752158    25.0          68.0
Bibb County    Alabama    20826.0   22915  7.122016    12.6          82.9
Blount County  Alabama    51024.0   57322  5.130910    13.4          82.0

ámbito
indicador              multiunit income med_income
name           state
Autauga County Alabama       7.2  24568      53255
Baldwin County Alabama      22.6  26469      50147
Barbour County Alabama      11.1  15875      33219
Bibb County    Alabama       6.6  19918      41770
Blount County  Alabama       3.7  21070      45549

Al igual que ocurre con las filas, se puede acceder a las columnas individualmente, mediante tuplas.

In [21]:
df_county[('population','pop2000')].head()
# df_county['population','pop2000'].head() # Funciona, pero no se recomienda

state    name
Alabama  Autauga County     43671.0
         Baldwin County    140415.0
         Barbour County     29038.0
         Bibb County        20826.0
         Blount County      51024.0
Name: (population, pop2000), dtype: float64

También se pueden omitir los valores del índice a partir de un nivel.

In [22]:
df_county['population'].head()

indicador                pop2000  pop2010
state   name
Alabama Autauga County   43671.0    54571
        Baldwin County  140415.0   182265
        Barbour County   29038.0    27457
        Bibb County      20826.0    22915
        Blount County    51024.0    57322

Para acceder a una columna en el nivel más bajo, hay que utilizar, como en el caso de las filas, `DataFrame.xs()`.

In [23]:
df_county.xs('pop2000', level='indicador', axis=1).head()

ámbito                  population
state   name
Alabama Autauga County     43671.0
        Baldwin County    140415.0
        Barbour County     29038.0
        Bibb County        20826.0
        Blount County      51024.0

Puede accederse a los elementos mediante el uso de varias (en este caso dos) tuplas.

In [24]:
df_county.loc[('Alabama','Autauga County'), ('population')]
#df_county.loc[('Alabama','Autauga County'), ('population','pop2000')]

indicador
pop2000    43671.0
pop2010    54571.0
Name: (Alabama, Autauga County), dtype: float64

También pueden accederse a los elementos  a través del nivel (o niveles) más bajos del índice.

In [ ]:
df_county.loc['Alabama', 'money'].head()

La función `DataFrame.groupby()` también puede aplicarse a índices de varios niveles. Acepta un parámetro, denominado `level`, que permite agrupar los datos según el valor del índice en un nivel (se vio anteriormente).

In [25]:
grupos_df = df_county.groupby(level=0)
for grupo, datos in grupos_df:
    print(grupo)
    display(datos.head())
    break;    # Solamente el primer grupo.

Alabama

ámbito                 population             money                        \
indicador                 pop2000 pop2010 fed_spend poverty homeownership
state   name
Alabama Autauga County    43671.0   54571  6.068095    10.6          77.5
        Baldwin County   140415.0  182265  6.139862    12.2          76.7
        Barbour County    29038.0   27457  8.752158    25.0          68.0
        Bibb County       20826.0   22915  7.122016    12.6          82.9
        Blount County     51024.0   57322  5.130910    13.4          82.0

ámbito
indicador              multiunit income med_income
state   name
Alabama Autauga County       7.2  24568      53255
        Baldwin County      22.6  26469      50147
        Barbour County      11.1  15875      33219
        Bibb County          6.6  19918      41770
        Blount County        3.7  21070      45549

Otro ejemplo. Agrupa por nombre de condado, y muestra los grupos que más elementos tienen.

In [26]:
df_county.groupby(level=1).size().nlargest(5)

name
Washington County    30
Jefferson County     25
Franklin County      24
Jackson County       23
Lincoln County       23
dtype: int64

### <font color="#5E5E5E"> Otros métodos de utilidad  </font>

Es posible crear un índice con uno de los niveles mediante `Index.get_level_values(nivel)`.

In [27]:
df_county.index.get_level_values('name')

Index(['Autauga County', 'Baldwin County', 'Barbour County', 'Bibb County',
       'Blount County', 'Bullock County', 'Butler County', 'Calhoun County',
       'Chambers County', 'Cherokee County',
       ...
       'Niobrara County', 'Park County', 'Platte County', 'Sheridan County',
       'Sublette County', 'Sweetwater County', 'Teton County', 'Uinta County',
       'Washakie County', 'Weston County'],
      dtype='str', name='name', length=3143)

A veces es más cómodo mostrar los índices de varios niveles como tuplas. Es posible hacerlo fijando la opción `display.multi_sparse` de *pandas* a `False`

In [28]:
pd.set_option('display.multi_sparse', False)
df_county.head()

,ámbito,population,population,money,money,money,money,money,money
,indicador,pop2000,pop2010,fed_spend,poverty,homeownership,multiunit,income,med_income
state,name,,,,,,,,
Alabama,Autauga County,43671.0,54571,6.068095,10.6,77.5,7.2,24568,53255
Alabama,Baldwin County,140415.0,182265,6.139862,12.2,76.7,22.6,26469,50147
Alabama,Barbour County,29038.0,27457,8.752158,25.0,68.0,11.1,15875,33219
Alabama,Bibb County,20826.0,22915,7.122016,12.6,82.9,6.6,19918,41770
Alabama,Blount County,51024.0,57322,5.130910,13.4,82.0,3.7,21070,45549

In [29]:
pd.set_option('display.multi_sparse', True)

<br>
<div align="right">
<a href="#inicio"><font size=5 color="#B51700"><i class="fa fa-arrow-circle-up" aria-hidden="true"></i></font></a>
</div>

---

<div align="right">
<font size=5 color="#B51700"><i class="fa fa-coffee" aria-hidden="true"></i></font>
</div>