<a id="inicio"></a>
<br><br><br>
<div align="left">
<h1><font size=6>Pandas</font></h1>
    <h2><font color="#5E5E5E" size=5>5. Acceso a datos</font>  </h2>
<br><br><br><br>
</div>


<div align="right">
<font color="#B51700" size=4><b>Análisis y visualización de datos</b></font><br><br>
<font  size=3>Máster Universitario en Ingeniería Informática</font><br>
<font  size=3>Máster Universitario en Big Data y Computación en la Nube</font><br>
<font size=3>Máster Universitario en Inteligencia Artificial</font><br><br>
<font color="#5E5E5E" size=3><b>Luis de la Ossa  &nbsp;&nbsp;</b></font><span style="background-color:#B51700; color:white; padding:2px 6px; font-family:Arial, sans-serif;font-weight:bold;font-size:18px;">UCLM</span>
</div>

---

In [1]:
import pandas as pd
import numpy as np

pd.__version__

'3.0.6'

En esta libreta se trabajará con este conjunto sintético de datos que se ha utilizado anteriormente.

In [2]:
import pandas as pd

types = {
    "Nombre": "str",
    "Producto": "str",
    "Apellido": "str",
    "Compra": "int64"
}
df_productos = pd.read_csv('data/productos.csv', dtype=types, index_col=0)

df_productos = df_productos[['Nombre', 'Apellido','Producto','Compra','Venta']]
df_productos

            Nombre   Apellido Producto  Compra  Venta
Tienda 1    Álvaro    Álvarez    Queso      15   22.5
Tienda 2    Benito    Benitez     Vino      10   14.5
Tienda 3  Fernando  Fernández    Jamón      35   50.0
Tienda 4    Martín   Martínez   Aceite      12   20.0
Tienda 2    Hernán  Hernández  Azafrán       3    5.0

---
## <font color="#5E5E5E">1. Acceso a columnas de un *DataFrame*</font>


El operador `[ ]` (en realidad es el método `__getitem__()`)  proporciona acceso a las columnas del `DataFrame`. Toma ***un** argumento* que puede ser:
* El nombre de una columna. En ese caso devuelve un objeto de tipo `Series`.
* *Una lista* con nombres de columnas únicos. En ese caso devuelve otro `DataFrame`.

En esta celda se accede, mediante el `string` con el nombre, al contenido de la columna `Producto` del `DataFrame` `df_productos`. El resultado es un objeto de tipo `Series`.

In [3]:
s_productos = df_productos['Producto']
s_productos

Tienda 1      Queso
Tienda 2       Vino
Tienda 3      Jamón
Tienda 4     Aceite
Tienda 2    Azafrán
Name: Producto, dtype: str

El uso de una lista de *strings* proporciona acceso a un conjunto de columnas, y devuelve otro `DataFrame`.

In [4]:
#columnas = ['Producto','Compra','Venta']
#df_productos[columnas]

df_productos[['Producto','Compra','Venta']]   # Equivalente

         Producto  Compra  Venta
Tienda 1    Queso      15   22.5
Tienda 2     Vino      10   14.5
Tienda 3    Jamón      35   50.0
Tienda 4   Aceite      12   20.0
Tienda 2  Azafrán       3    5.0

La lista de nombres puede tener tamaño uno. En ese caso, se devuelve un `DataFrame` con una columna (en lugar de una *Serie*).

In [5]:
df_productos[['Producto']]

         Producto
Tienda 1    Queso
Tienda 2     Vino
Tienda 3    Jamón
Tienda 4   Aceite
Tienda 2  Azafrán

<div class="alert alert-block alert-danger">
    
<i class="fa fa-exclamation-triangle" aria-hidden="true"></i>
Un error muy común a la hora de acceder a varias columnas consiste en utilizar como argumentos los nombres de las columnas separados por comas, en lugar de ___una colección___ con los nombres de las columnas.
</div>

In [8]:
#df_productos['Producto','Compra','Venta']  # Devuelve error.

<div class="alert alert-block alert-warning">

<i class="fa fa-exclamation-circle" aria-hidden="true"></i>
Es posible acceder a las columnas como un campo del `DataFrame` si el nombre es compatible con un identificador de *Python* y no entra en conflicto con atributos existentes. Por ejemplo: `df_productos.Producto`. Sin embargo, **es recomendable no utilizar este tipo de notación** o, sobre todo, no mezclar los tipos de anotación.
</div>



###  <font color="#5E5E5E"> Acceso a las columnas en función de su tipo </font>

En algunas situaciones puede ser necesario seleccionar las columnas cuyos elementos son de un tipo determinado. El método, `DataFrame.select_dtypes()` ofrece versatilidad, y permite determinar las columnas de qué tipos se incluyen (parámetro `include`) y qué tipos se excluyen (parámetro `exclude`). Para la identificación de los tipos se pueden utilizar tanto nombres de tipos escritos como cadenas (`"float64"`) como tipos de datos implementados en _Numpy_ (`np.float64`). En las siguientes celdas se accede a las columnas numéricas del `DataFrame` `df_productos` pero excluyendo las que usan el tipo de datos `float64`.

In [11]:
df_productos.info()

<class 'pandas.DataFrame'>
Index: 5 entries, Tienda 1 to Tienda 2
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Nombre    5 non-null      str
 1   Apellido  5 non-null      str
 2   Producto  5 non-null      str
 3   Compra    5 non-null      int64
 4   Venta     5 non-null      float64
dtypes: float64(1), int64(1), str(3)
memory usage: 412.0+ bytes

In [17]:
df_productos.select_dtypes(include='number', exclude=np.float64)
#df_productos.select_dtypes(exclude=np.float64)
#df_productos.select_dtypes(include="str")

          Compra
Tienda 1      15
Tienda 2      10
Tienda 3      35
Tienda 4      12
Tienda 2       3

<div class="alert alert-block alert-warning">
    
<i class="fa fa-exclamation-circle" aria-hidden="true"></i>
Hay un mundo en relación a los tipos de datos en *numpy*, pero para el usuario de *pandas* o las librerías que se verán en el curso (para la inmensa mayoría de los profesionales) *raramente se ha de recurrir a esta información* [**( + inf )**](https://docs.scipy.org/doc/numpy/reference/arrays.scalars.html).
</div>



###  <font color="#5E5E5E"> Iteración sobre columnas</font>

El método `DataFrame.items()`devuelve las columnas del `DataFrame` como un iterador de pares `(nombre, serie)`.

In [18]:
next(df_productos.items())

('Nombre',
 Tienda 1      Álvaro
 Tienda 2      Benito
 Tienda 3    Fernando
 Tienda 4      Martín
 Tienda 2      Hernán
 Name: Nombre, dtype: str)

<br>

---
## <font color="#5E5E5E">2. Acceso a filas (elementos) mediante índice: `.loc[]`</font>


El acceso a filas de un `DataFrame`, o a los elementos de una `Series`, **se debe hacer** (están concebidos para ello) a través de su índice, mediante el método `DataFrame.loc[idx]`/`Series.loc[idx]`. Recibe un **único** argumento,  `idx`, que puede ser:

* un valor, identificador de un elemento del índice;
* una lista de valores, identificadores de elementos del índice.

<div class="alert alert-block alert-info">
    
<i class="fa fa-info-circle" aria-hidden="true"></i> En este caso se verá acceso mediante valores del índice. Más adelante se verán más posibilidades.
</div>


### <font color="#5E5E5E">  Acceso mediante un valor </font>


`DataFrame.loc[idx]`, cuando `idx` es un valor, devuelve la *fila o filas* correspondientes del `DataFrame`. Si el valor del índice corresponde a una sola fila, ésta se devuelve en forma de `Series`.

In [23]:
df_productos

            Nombre   Apellido Producto  Compra  Venta
Tienda 1    Álvaro    Álvarez    Queso      15   22.5
Tienda 2    Benito    Benitez     Vino      10   14.5
Tienda 3  Fernando  Fernández    Jamón      35   50.0
Tienda 4    Martín   Martínez   Aceite      12   20.0
Tienda 2    Hernán  Hernández  Azafrán       3    5.0

In [24]:
df_productos.loc['Tienda 1']

Nombre       Álvaro
Apellido    Álvarez
Producto      Queso
Compra           15
Venta          22.5
Name: Tienda 1, dtype: object

Si el índice corresponde a varias filas **(puede ser)**, el resultado es, a su vez, otro `DataFrame`.

In [25]:
df_productos.loc['Tienda 2']

          Nombre   Apellido Producto  Compra  Venta
Tienda 2  Benito    Benitez     Vino      10   14.5
Tienda 2  Hernán  Hernández  Azafrán       3    5.0

En cuanto al acceso a `Series`, el resultado depende también del número de elementos correspondientes al índice. Cuando el índice corresponde a un elemento, se devuelve un escalar.

In [26]:
s_productos.loc['Tienda 1']

'Queso'

Cuando el índice corresponde a varios elementos,  se devuelve otra `Series`.

In [27]:
s_productos.loc['Tienda 2']

Tienda 2       Vino
Tienda 2    Azafrán
Name: Producto, dtype: str



### <font color="#5E5E5E">  Acceso mediante una colección de valores </font>


`DataFrame.loc[idx]` acepta como argumento una *secuencia* de valores, y devuelve siempre un nuevo `DataFrame` con las filas seleccionadas.

In [28]:
df_productos.loc[['Tienda 1', 'Tienda 2']]
#df_productos.loc[['Tienda 1']]

          Nombre   Apellido Producto  Compra  Venta
Tienda 1  Álvaro    Álvarez    Queso      15   22.5
Tienda 2  Benito    Benitez     Vino      10   14.5
Tienda 2  Hernán  Hernández  Azafrán       3    5.0

En el caso de `Series.loc[idx]`, cuando `idx` es una colección, el método devuelve siempre otra `Series`.

In [29]:
s_productos.loc[['Tienda 1', 'Tienda 2']]
#s_productos.loc[['Tienda 1']]

Tienda 1      Queso
Tienda 2       Vino
Tienda 2    Azafrán
Name: Producto, dtype: str

### <font color="#5E5E5E">  <i>slicing</i></font>


El método `Dataframe.loc[idx]`/`Series.loc[idx]` también permite especificar el conjunto de valores `idx` mediante *slicing*, independientemente del tipo de datos utilizado en el índice. Por ejemplo, en la siguente celda obtiene las filas que van desde `Tienda 1` hasta `Tienda 3`.

In [30]:
df_productos

            Nombre   Apellido Producto  Compra  Venta
Tienda 1    Álvaro    Álvarez    Queso      15   22.5
Tienda 2    Benito    Benitez     Vino      10   14.5
Tienda 3  Fernando  Fernández    Jamón      35   50.0
Tienda 4    Martín   Martínez   Aceite      12   20.0
Tienda 2    Hernán  Hernández  Azafrán       3    5.0

In [31]:
df_productos.loc['Tienda 1':'Tienda 3']

            Nombre   Apellido Producto  Compra  Venta
Tienda 1    Álvaro    Álvarez    Queso      15   22.5
Tienda 2    Benito    Benitez     Vino      10   14.5
Tienda 3  Fernando  Fernández    Jamón      35   50.0

El funcionamiento es similar en *Series*.

In [32]:
s_productos.loc['Tienda 1':'Tienda 3']

Tienda 1    Queso
Tienda 2     Vino
Tienda 3    Jamón
Name: Producto, dtype: str

<div class="alert alert-block alert-danger">
    
<i class="fa fa-exclamation-triangle" aria-hidden="true"></i>
__Importante:__ Los elementos utilizados para definir los límites del intervalo deben ser *únicos* en el índice. Por otra parte, el  *slicing* incluye el límite derecho. 
</div>

En el ejemplo anterior se aprecia que, al hacer *slicing*, queda fuera una de las filas correspondientes a `Tienda 2` (la última fila). **Es muy importante ser consciente del orden que guardan las filas** (o de si no tienen por qué guardarlo) al hacer este tipo de acceso. Debido a esto, prácticamente siempre es necesario ordenar las filas del `DataFrame` en función del valor de su índice mediante el método `DataFrame.sort_index()`.

In [33]:
df_productos.sort_index().loc['Tienda 1':'Tienda 3']

            Nombre   Apellido Producto  Compra  Venta
Tienda 1    Álvaro    Álvarez    Queso      15   22.5
Tienda 2    Benito    Benitez     Vino      10   14.5
Tienda 2    Hernán  Hernández  Azafrán       3    5.0
Tienda 3  Fernando  Fernández    Jamón      35   50.0

<div class="alert alert-block alert-info">
    
<i class="fa fa-info-circle" aria-hidden="true"></i> Los índices de cada tipo ofrecen funcionalidades específicas. En el caso de índices alfanuméricos, se puede hacer _slicing_ lexicográfico con los prefijos, sin necesidad de especificar los valores concretos de los elementos. Los índices de datos temporales, por ejemplo, ofrecen funcionalidades muy completas y complejas que se verán en el módulo correspondiente.
</div>

In [34]:
df_productos.set_index('Producto').sort_index().loc['Az':'Vi']
#df_productos.set_index('Producto').sort_index().loc['Az':'Vino']

            Nombre   Apellido  Compra  Venta
Producto
Azafrán     Hernán  Hernández       3    5.0
Jamón     Fernando  Fernández      35   50.0
Queso       Álvaro    Álvarez      15   22.5

Una alternativa (poco usada) al *slicing* es `DataFrame.truncate()`, que requiere el eje ordenado y conserva los límites.

In [35]:
df_productos.sort_index().truncate(before='Tienda 2', after='Tienda 3')

            Nombre   Apellido Producto  Compra  Venta
Tienda 2    Benito    Benitez     Vino      10   14.5
Tienda 2    Hernán  Hernández  Azafrán       3    5.0
Tienda 3  Fernando  Fernández    Jamón      35   50.0

###  <font color="#5E5E5E"> Selección con etiquetas que pueden no existir.</font>

Cuando se seleccionan filas a partir de un conjunto de etiquetas, y alguna de las etiquetas del conjunto no corresponde a ninguna entrada del índice (y por tanto a ninguna fila), se produce una excepción. Si en lugar de eso simplemente se quieren descartar esas etiquetas, se puede hacer de dos formas. 

Si el índice del `DataFrame` original es único, resultado del método `DataFrame.reindex(labels)` en cierto modo, es equivalente a una selección. Otra opción consiste en utilizar una intersección : `DataFrame.loc[DataFrame.index.intersection(labels)]`.
</div>

In [36]:
etiquetas = ['Tienda 1', 'Tienda 2', 'Tienda 6']
# df_productos.reindex(etiquetas) # Salta excepción porque `Tienda 2` aparece dos veces.
df_productos.loc[df_productos.index.intersection(etiquetas)]

          Nombre   Apellido Producto  Compra  Venta
Tienda 1  Álvaro    Álvarez    Queso      15   22.5
Tienda 2  Benito    Benitez     Vino      10   14.5
Tienda 2  Hernán  Hernández  Azafrán       3    5.0


###  <font color="#5E5E5E"> Iteración sobre filas</font>


El método `DataFrame.iterrows()` permite iterar sobre las filas de un `DataFrame`. Devuelve pares (índice, `Series`), de forma que la correpsondiente a cada fila tiene un único `dtype`.

In [37]:
for idx, row in df_productos.iterrows():           
    print(idx, end=' --> ')                        
    print(row['Producto'])

Tienda 1 --> Queso
Tienda 2 --> Vino
Tienda 3 --> Jamón
Tienda 4 --> Aceite
Tienda 2 --> Azafrán

El método `DataFrame.itertuples()` devuelve tuplas con nombres de campo. Es más eficiente que `DataFrame.iterrows()` y preserva los tipos de datos.

In [38]:
for row in df_productos.itertuples(): 
    print(row)
    #print(row.Nombre, row.Producto)

Pandas(Index='Tienda 1', Nombre='Álvaro', Apellido='Álvarez', Producto='Queso', Compra=15, Venta=22.5)
Pandas(Index='Tienda 2', Nombre='Benito', Apellido='Benitez', Producto='Vino', Compra=10, Venta=14.5)
Pandas(Index='Tienda 3', Nombre='Fernando', Apellido='Fernández', Producto='Jamón', Compra=35, Venta=50.0)
Pandas(Index='Tienda 4', Nombre='Martín', Apellido='Martínez', Producto='Aceite', Compra=12, Venta=20.0)
Pandas(Index='Tienda 2', Nombre='Hernán', Apellido='Hernández', Producto='Azafrán', Compra=3, Venta=5.0)

---
##  <font color="#5E5E5E"> 3. Acceso a elementos en `DataFrames`</font>


Con `DataFrame.loc[idx, col]` se accede a los elementos dados el valor (o valores) de su índice y columnas. Tanto `idx` como `col` pueden ser un valor, o una colección de valores, que puede definirse mediante *slicing*.

In [39]:
df_productos.loc[['Tienda 2','Tienda 1'],'Producto']
#df_productos.loc[['Tienda 2','Tienda 1'],['Producto']]

Tienda 2       Vino
Tienda 2    Azafrán
Tienda 1      Queso
Name: Producto, dtype: str

In [40]:
df_productos.loc[['Tienda 2','Tienda 1'],['Producto','Compra','Venta']]

         Producto  Compra  Venta
Tienda 2     Vino      10   14.5
Tienda 2  Azafrán       3    5.0
Tienda 1    Queso      15   22.5

In [41]:
df_productos.loc['Tienda 1':'Tienda 3',['Producto','Compra','Venta']]

         Producto  Compra  Venta
Tienda 1    Queso      15   22.5
Tienda 2     Vino      10   14.5
Tienda 3    Jamón      35   50.0

<div class="alert alert-block alert-warning">
    
<i class="fa fa-exclamation-circle" aria-hidden="true"></i>
Es frecuente ver código en el que se accede a los elementos por índice, y se accede después a la columna resultante, es decir `DataFrame.loc[idx][col]` . Aunque en consultas el comportamiento es el esperado, *no se debe utilizar este tipo de acceso*, sobre todo si se va a escribir sobre `DataFrame` seleccionado. Esta circunstancia se tratará con detalle en una sección posterior.
</div>



### <font color="#5E5E5E">  El método `.at[]`</font>

El método  `Dataframe.at[idx, col]` es equivalente a `Dataframe.loc[idx,col]`, pero con una salvedad: solo admite escalares como argumentos, es decir, **no admite colecciones**. Sin embargo, es más eficiente.

In [42]:
df_productos.at['Tienda 1', 'Apellido']

'Álvarez'

<br>

---
##  <font color="#5E5E5E"> 4. Acceso para escritura</font>


El acceso  para escritura en `Series` y `DataFrame` es similar al acceso para lectura. Pero debe haber una correspondencia entre las posiciones accedidas y los valores asignados.

<div class="alert alert-block alert-warning">
    
<i class="fa fa-exclamation-circle" aria-hidden="true"></i>
Para ilustrar el siguiente ejemplo, se copiará el contenido de la columna `df_productos['Producto']` en la serie `s_productos`.  Debido a que *pandas* desde la versión 3.0 usa *copy-on-write*, la copia se hace de forma implícita cuando se produce una escritura en la `Serie`, de modo que no se altera el `DataFrame` original.
</div>

In [43]:
s_productos = df_productos['Producto']
s_productos

Tienda 1      Queso
Tienda 2       Vino
Tienda 3      Jamón
Tienda 4     Aceite
Tienda 2    Azafrán
Name: Producto, dtype: str

In [44]:
#df_productos

Si se asigna un escalar a varias posiciones de un objeto *Series*, se escribe en todas ellas.

In [45]:
s_productos.loc[['Tienda 1','Tienda 3']]='Jamón'
s_productos

Tienda 1      Jamón
Tienda 2       Vino
Tienda 3      Jamón
Tienda 4     Aceite
Tienda 2    Azafrán
Name: Producto, dtype: str

Cuando se asigna una colección de valores a varias posiciones de una `Series`, las dimensiones de ambos conjuntos han de ser similares (salvo en el caso en que se asignen escalares, como se ha visto).

In [46]:
s_productos.loc['Tienda 1'] = 'Vermut'  
#s_productos.loc[['Tienda 1','Tienda 3']]=['Vermut', 'Chorizo']
#s_productos.loc[['Tienda 1','Tienda 3']]=['Vermut', 'Vermut', 'Vermut']      # Error por la diferencia de tamaños
#s_productos.loc[['Tienda 1','Tienda 2']]=['Vermut', 'Chorizo']                # Error por la diferencia de tamaños
s_productos

Tienda 1     Vermut
Tienda 2       Vino
Tienda 3      Jamón
Tienda 4     Aceite
Tienda 2    Azafrán
Name: Producto, dtype: str

Si se asigna un valor a un nuevo índice, se añade un nuevo elemento a la serie.

In [ ]:
#s_productos.loc['Tienda 5']

In [47]:
s_productos.loc['Tienda 5'] = 'Tomates'
s_productos

Tienda 1     Vermut
Tienda 2       Vino
Tienda 3      Jamón
Tienda 4     Aceite
Tienda 2    Azafrán
Tienda 5    Tomates
Name: Producto, dtype: str

En el caso de los `DataFrame`, también se puede asignar un valor escalar a varios elementos, siempre y cuando el tipo de datos sea compatible.

In [48]:
df_productos.loc[['Tienda 1','Tienda 2'],['Compra', 'Venta']]=10
# df_productos.loc[['Tienda 1','Tienda 2'],['Compra', 'Venta']]=10.5.  # Se produce excepción porque `Compra` es un entero.`
df_productos

            Nombre   Apellido Producto  Compra  Venta
Tienda 1    Álvaro    Álvarez    Queso      10   10.0
Tienda 2    Benito    Benitez     Vino      10   10.0
Tienda 3  Fernando  Fernández    Jamón      35   50.0
Tienda 4    Martín   Martínez   Aceite      12   20.0
Tienda 2    Hernán  Hernández  Azafrán      10   10.0

Igualmente, cuando se asigna una colección de valores, el tamaño de conjunto de datos y de las posiciones deben coincidir.

In [49]:
df_productos.loc[['Tienda 1','Tienda 2'],'Venta']=[22, 14.5, 0]
df_productos

            Nombre   Apellido Producto  Compra  Venta
Tienda 1    Álvaro    Álvarez    Queso      10   22.0
Tienda 2    Benito    Benitez     Vino      10   14.5
Tienda 3  Fernando  Fernández    Jamón      35   50.0
Tienda 4    Martín   Martínez   Aceite      12   20.0
Tienda 2    Hernán  Hernández  Azafrán      10    0.0

También se puede escribir el valor de columnas completas. Al igual que anteriormente, han de coincidir los tamaños.

In [50]:
df_productos['Producto'] = ['Queso manchego', 'Vino manchego', 
                            'Jamón extremeño', 'Aceite andaluz', 'Azafrán manchego']
df_productos

            Nombre   Apellido          Producto  Compra  Venta
Tienda 1    Álvaro    Álvarez    Queso manchego      10   22.0
Tienda 2    Benito    Benitez     Vino manchego      10   14.5
Tienda 3  Fernando  Fernández   Jamón extremeño      35   50.0
Tienda 4    Martín   Martínez    Aceite andaluz      12   20.0
Tienda 2    Hernán  Hernández  Azafrán manchego      10    0.0

<br>

### <font color="#5E5E5E"> Creación de nuevas columnas </font>


Si el nombre no existe, la asignación crea una columna. Una lista aporta un valor por fila en el orden actual; un escalar se repite; una `Series` se alinea con las etiquetas del índice del `DataFrame`.

In [51]:
df_productos['C.P'] = ['02001', '02001', '02003', '02004','02004']
df_productos

            Nombre   Apellido          Producto  Compra  Venta    C.P
Tienda 1    Álvaro    Álvarez    Queso manchego      10   22.0  02001
Tienda 2    Benito    Benitez     Vino manchego      10   14.5  02001
Tienda 3  Fernando  Fernández   Jamón extremeño      35   50.0  02003
Tienda 4    Martín   Martínez    Aceite andaluz      12   20.0  02004
Tienda 2    Hernán  Hernández  Azafrán manchego      10    0.0  02004

In [52]:
df_productos['Localidad'] = 'Albacete'
df_productos

,Nombre,Apellido,Producto,Compra,Venta,C.P,Localidad
Tienda 1,Álvaro,Álvarez,Queso manchego,10,22.0,02001,Albacete
Tienda 2,Benito,Benitez,Vino manchego,10,14.5,02001,Albacete
Tienda 3,Fernando,Fernández,Jamón extremeño,35,50.0,02003,Albacete
Tienda 4,Martín,Martínez,Aceite andaluz,12,20.0,02004,Albacete
Tienda 2,Hernán,Hernández,Azafrán manchego,10,0.0,02004,Albacete

In [53]:
df_productos['Entregado'] = pd.Series({'Tienda 1': True, 'Tienda 2': True}, dtype='boolean')
df_productos

,Nombre,Apellido,Producto,Compra,Venta,C.P,Localidad,Entregado
Tienda 1,Álvaro,Álvarez,Queso manchego,10,22.0,02001,Albacete,True
Tienda 2,Benito,Benitez,Vino manchego,10,14.5,02001,Albacete,True
Tienda 3,Fernando,Fernández,Jamón extremeño,35,50.0,02003,Albacete,<NA>
Tienda 4,Martín,Martínez,Aceite andaluz,12,20.0,02004,Albacete,<NA>
Tienda 2,Hernán,Hernández,Azafrán manchego,10,0.0,02004,Albacete,True

<div class="alert alert-block alert-info">
    
<i class="fa fa-info-circle" aria-hidden="true"></i>  Se pueden intercambiar valores de columnas: `df[['B', 'A']] = df[['A', 'B']]`, pero esto no funciona con `df.loc[:, ['B', 'A']] = df[['A', 'B']]` porque `.loc[]` alinea los ejes. 
</div>

---

<br>

## <font color="#5E5E5E"> <i class="fa fa-plus-circle" aria-hidden="true"></i> 5. Acceso por posición `.iloc[]`, `.iat[]`.  </font>

Aunque el acceso a filas de un `DataFrame` o elementos de una `Series` **se debe hacer mediante el índice**, también es posible hacerlo por su posición, del mismo modo que se hace en el resto de colecciones de *python* o *numpy*.
<div class="alert alert-block alert-danger">
    
<i class="fa fa-exclamation-triangle" aria-hidden="true"></i> Ha de evitarse el acceso a los datos por posición a menos que sea necesario. No es una práctica prohibída, pero implica tener que controlar el orden, y es más fácil que se produzcan errores.
</div>

### <font color="#5E5E5E">  Acceso a filas y elementos por posición: `.iloc[]` </font>



Se puede acceder a las filas de un `DataFrame` o a los elementos de una `Series` mediante `DataFrame.iloc[pos]/Series.iloc[pos]`, donde `pos` es un número entero que representa la posición. El funcionamiento de `DataFrame.iloc[pos]` es similar al de `DataFrame.loc[idx]`. Toma **un argumento** que puede ser un valor entero (en este caso una posición), o una colección de enteros que puede representarse con *slicing*.  En el primer caso, devuelve una `Series` con la fila correspondiente.

In [54]:
df_productos.iloc[0]

Nombre               Álvaro
Apellido            Álvarez
Producto     Queso manchego
Compra                   10
Venta                  22.0
C.P                   02001
Localidad          Albacete
Entregado              True
Name: Tienda 1, dtype: object

En caso de utilizar una colección, devuelve un `DataFrame` con las filas correspondientes.

In [55]:
df_productos.iloc[[1,3,4]]

,Nombre,Apellido,Producto,Compra,Venta,C.P,Localidad,Entregado
Tienda 2,Benito,Benitez,Vino manchego,10,14.5,02001,Albacete,True
Tienda 4,Martín,Martínez,Aceite andaluz,12,20.0,02004,Albacete,<NA>
Tienda 2,Hernán,Hernández,Azafrán manchego,10,0.0,02004,Albacete,True

El uso de *slicing* es equivalente al uso de una colección de enteros.

In [56]:
df_productos.iloc[0:3]

,Nombre,Apellido,Producto,Compra,Venta,C.P,Localidad,Entregado
Tienda 1,Álvaro,Álvarez,Queso manchego,10,22.0,02001,Albacete,True
Tienda 2,Benito,Benitez,Vino manchego,10,14.5,02001,Albacete,True
Tienda 3,Fernando,Fernández,Jamón extremeño,35,50.0,02003,Albacete,<NA>

En el caso de `Series.iloc[pos]`, cuando `pos` es un entero, devuelve elemento correspondiente.

In [57]:
s_productos.iloc[4]

'Azafrán'

Cuando es una colección de enteros, devuelve la otra `Series` con los elementos.

In [58]:
df_productos.iloc[0:3]

,Nombre,Apellido,Producto,Compra,Venta,C.P,Localidad,Entregado
Tienda 1,Álvaro,Álvarez,Queso manchego,10,22.0,02001,Albacete,True
Tienda 2,Benito,Benitez,Vino manchego,10,14.5,02001,Albacete,True
Tienda 3,Fernando,Fernández,Jamón extremeño,35,50.0,02003,Albacete,<NA>

El método `DataFrame.take()` es parecido a `DataFrame.iloc[]`.

In [59]:
df_productos.take([1, 3, 4])

,Nombre,Apellido,Producto,Compra,Venta,C.P,Localidad,Entregado
Tienda 2,Benito,Benitez,Vino manchego,10,14.5,02001,Albacete,True
Tienda 4,Martín,Martínez,Aceite andaluz,12,20.0,02004,Albacete,<NA>
Tienda 2,Hernán,Hernández,Azafrán manchego,10,0.0,02004,Albacete,True



### <font color="#5E5E5E">  Acceso al elementos por posición</font>

También es posible acceder a elementos, o conjuntos de elementos, por posición mediante `DataFrame.iloc[pos,col]`, donde `pos` y `col` pueden ser tanto enteros como colecciones de enteros.

In [60]:
df_productos.iloc[2,1]

'Fernández'

In [61]:
df_productos.iloc[0:3,0:2]

            Nombre   Apellido
Tienda 1    Álvaro    Álvarez
Tienda 2    Benito    Benitez
Tienda 3  Fernando  Fernández

<br>

### <font color="#5E5E5E">  El método `.iat[]`</font>

El método `Dataframe.iat[idx, col]` permite acceder a elementos por posición, pero tanto `idx` como `col` han de ser valores enteros, y el valor devuelto es un escalar.

In [62]:
df_productos.iat[2,1]

'Fernández'

<br>

---
## <font color="#5E5E5E"> <i class="fa fa-plus-circle" aria-hidden="true"></i> 6. Ejes y conversión a arrays </font>


Un `DataFrame` organiza los datos en filas y columnas. Se puede acceder a los dos índices (y sus etiquetas) mediante los atributos:

* `index`: contiene las etiquetas de las filas.
* `columns`: contiene las etiquetas de las columnas.

Las etiquetas de los índices ***deben distinguirse de los datos***.

In [63]:
df_productos.index

Index(['Tienda 1', 'Tienda 2', 'Tienda 3', 'Tienda 4', 'Tienda 2'], dtype='str')

In [64]:
df_productos.columns

Index(['Nombre', 'Apellido', 'Producto', 'Compra', 'Venta', 'C.P', 'Localidad',
       'Entregado'],
      dtype='str')



### <font color="#5E5E5E">  Etiquetas como arrays y listas</font>


El atributo `array` de un `Index` permite acceder al array que contiene sus etiquetas. Devuelve un `ExtensionArray`: una estructura de pandas cuya implementación depende del tipo de los datos. Esta se puede convertir en una lista mediante el método `tolist()`.

In [65]:
df_productos.columns.array
#df_productos.columns.tolist()

<StringArray>
[   'Nombre',  'Apellido',  'Producto',    'Compra',     'Venta',       'C.P',
 'Localidad', 'Entregado']
Length: 8, dtype: str

### <font color="#5E5E5E"> Conversión de `DataFrame` a arrays *NumPy*</font>


El método `to_numpy()` devuelve los datos como un array bidimensional de NumPy (`ndarray`). Conserva el orden de las filas y columnas, pero no incluye los índices (ni, por tanto, sus etiquetas). 

Un array de NumPy tiene un único `dtype`, por lo que pandas debe buscar un tipo común para todas las columnas. La conversión de tipos puede requerir copiar los datos y cambiar su representación. No modifica los tipos de las columnas del `DataFrame` original.

In [66]:
datos_numpy = df_productos.to_numpy()

# Muestra las dos primeras filas.
datos_numpy[:2]

array([['Álvaro', 'Álvarez', 'Queso manchego', 10, 22.0, '02001',
        'Albacete', True],
       ['Benito', 'Benitez', 'Vino manchego', 10, 14.5, '02001',
        'Albacete', True]], dtype=object)

In [67]:
datos_numpy.dtype

dtype('O')

In [68]:
# Al seleccionar solo las columnas numéricas, se obtiene un array de números decimales.
df_productos[['Compra', 'Venta']].to_numpy()

array([[10. , 22. ],
       [10. , 14.5],
       [35. , 50. ],
       [12. , 20. ],
       [10. ,  0. ]])

### <font color="#5E5E5E"> Conversión de `Series`</font>

La secuencia de valores de un objeto `Series` se puede obtener de dos maneras:

* `serie.array`: devuelve un `ExtensionArray` y conserva el tipo de datos de pandas.
* `serie.to_numpy()`: devuelve un `ndarray` de NumPy, lo que puede requerir una conversión y una copia.

En ambos casos se obtiene una estructura unidimensional, sin las etiquetas del índice. 

La distinción es especialmente útil con los tipos de texto de pandas 3.0. Su representación en pandas utiliza arrays específicos; al convertirlos a NumPy podemos obtener un array de tipo `object`. Por otra parte, la clase concreta que muestra `.array` puede variar según el tipo y el almacenamiento utilizado, por ejemplo, con o sin PyArrow.

También existe el atributo `.values`, tanto en `Series` como en `DataFrame`. Es público y se puede utilizar, pero preferimos `.array` o `.to_numpy()` porque expresan con mayor claridad qué representación necesitamos. Un `DataFrame` no dispone de un atributo `.array`.

<div class="alert alert-block alert-info">
    
<i class="fa fa-info-circle" aria-hidden="true"></i>  Tanto en `Series` como `DataFrame` disponen de un atributo público, `.values`, pero se recomiendan los métodos indicados. Un `DataFrame` no dispone de un atributo `.array`.
</div>

In [69]:
s_texto = df_productos['Producto']

s_texto.array

<StringArray>
[  'Queso manchego',    'Vino manchego',  'Jamón extremeño',
   'Aceite andaluz', 'Azafrán manchego']
Length: 5, dtype: str

In [70]:
s_texto.to_numpy()

array(['Queso manchego', 'Vino manchego', 'Jamón extremeño',
       'Aceite andaluz', 'Azafrán manchego'], dtype=object)

### <font color="#5E5E5E"> Arrays, copias y `Copy-on-Write`</font>



Un array de NumPy que comparte memoria con un objeto de pandas se devuelve como **solo lectura**. Así se evita modificar indirectamente el objeto original escribiendo en ese array.

Esto no ocurre con el atributo `.array` que respalda la serie y no crea una copia independiente. Modificarlo directamente puede eludir Copy-on-Write y afectar a los datos originales.

In [71]:
df_numerico = pd.DataFrame({'Valor': [10, 20, 30]})

matriz = df_numerico.to_numpy()

# En este ejemplo devuelve False: el array es de solo lectura.
matriz.flags.writeable

# Descomentar esta asignación produciría un ValueError.
# matriz[0, 0] = 99

False

Si se necesita modificar los valores del array por separado, se puede producir una copia mediante `to_numpy(copy=True)`.

In [72]:
matriz_copia = df_numerico.to_numpy(copy=True)
matriz_copia[0, 0] = 99

matriz_copia

array([[99],
       [20],
       [30]])

In [73]:
df_numerico

   Valor
0     10
1     20
2     30

<br>
<div align="right">
<a href="#inicio"><font size=5 color="#B51700"><i class="fa fa-arrow-circle-up" aria-hidden="true"></i></font></a>
</div>

---

<div align="right">
<font size=5 color="#B51700"><i class="fa fa-coffee" aria-hidden="true"></i></font>
</div>